// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: testtable.sql

package sqlc

import (
	"context"
	"database/sql"
)

const insertTesttable = `-- name: InsertTesttable :one
INSERT INTO testtable (label, alias)
VALUES ($1, $2)
    RETURNING id
`

type InsertTesttableParams struct {
	Label sql.NullString
	Alias int64
}

func (q *Queries) InsertTesttable(ctx context.Context, arg InsertTesttableParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTesttable, arg.Label, arg.Alias)
	var id int64
	err := row.Scan(&id)
	return id, err
}
